name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout Checkmarx cli
        uses: actions/checkout@v2
        with:
          name: Checkmarx/ast-cli     <-- clone https://github.com/org1/repo1
          ref: refs/heads/main
      - name: Install ninja with choco
        run: |
          choco install ninja
          ninja --version
