#
# Example job using github action to run a scan in a windows environment
#
# CLI installed using 'engineerd/configurator' action
#
# Configuration through environment secrets in Github
#

name: Checkmarx One Scan on Push
on:
  push:
    branches:
      - main
      

      
env:
  CX_PROJECT_NAME: ${{ secrets.CX_PROJECT_NAME }}
  CX_BRANCH: ${{ secrets.CX_BRANCH }}
  BRANCH_REFS: ${{ github.head_ref || github.ref }}
  CX_TENANT: ${{ secrets.CX_TENANT }}
  CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
  CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
  CX_ADDITIONAL_PARAMS: ${{ secrets.CX_ADDITIONAL_PARAMS }}

jobs:
  Scan:
    runs-on: windows-latest
    steps:
      - name: Create Checkmarx One Scan
        run: |
          echo "${BRANCH_REFS}"
