#
# Example job using github action to run a scan in a windows environment
#
# CLI installed using 'engineerd/configurator' action
#
# Configuration through environment secrets in Github
#

name: Checkmarx One Scan on Push

on:
  push:
    branches:
      - main
    
jobs:
  Scan:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Checkmarx One CLI
        run: |
          choco install wget --no-progress
          wget -r -l1 -np "https://github.com/CheckmarxDev/ast-cli/releases/latest/download/" -A "ast-cli*.zip"
          
