#
# Example job using github action to run a scan in a windows environment
#
# CLI installed using 'engineerd/configurator' action
#
# Configuration through environment secrets in Github
#

name: Checkmarx One Scan on Push
on:
  push:
    branches:
      - main
      
env:
  CX_PROJECT_NAME: ${{ secrets.CX_PROJECT_NAME }}
  CX_BRANCH: ${{ secrets.CX_BRANCH }}
  CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
  CX_TENANT: ${{ secrets.CX_TENANT }}
  CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
  CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
  CX_ADDITIONAL_PARAMS: ${{ secrets.CX_ADDITIONAL_PARAMS }}

jobs:
  Scan:
    runs-on: windows-latest
    steps:
      - name: Get Checkmarx One CLI
        run: |
          $latestRelease = Invoke-WebRequest https://github.com/CheckmarxDev/ast-cli/releases/latest -Headers @{"Accept"="application/json"}
          $json = $latestRelease.Content | ConvertFrom-Json
          $latestVersion = $json.tag_name
          $latestVersion 
          choco install wget --no-progress
          wget https://github.com/Checkmarx/ast-cli/releases/download/$latestVersion/ast-cli_${$latestVersion}_windows_x64.zip
          7z x ast-cli_2.0.31_windows_x64.zip
