name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      
jobs:
  Scan:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: wget
        run: wget https://github.com/Checkmarx/ast-cli/releases/download/2.0.31/ast-cli_2.0.31_windows_x64.zip
