name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      
jobs:
  Checkmarx-One-Scan:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get CLI
        uses: engineerd/configurator@v0.0.8
        with:
          name: "cx.exe"
          url: "https://github.com/Checkmarx/ast-cli/releases/download/2.0.31/ast-cli_2.0.31_windows_x64.zip"
          pathInArchive: "./cx.exe"
      - name: Testing
        run: |
          cx --help
          
