name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      
jobs:
  Checkmarx-One-Scan:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get CLI
        uses: engineerd/configurator@v0.0.8
        with:
          name: "hb3.exe"
          url: "https://get.helm.sh/helm-v3.0.0-beta.3-windows-amd64.zip"
          pathInArchive: "windows-amd64/helm.exe"
      - name: Testing
        run: |
          hb3 --help
          
