name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  Checkmarx-One-Scan:
    runs-on: windows-latest
    env:
      GOPRIVATE: "github.com/checkmarxDev/*"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          repository: Checkmarx/ast-cli
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Go Build
        run: go build -o ./bin/cx ./cmd
        
      - name: List files
        run: ls
      - name: List files up
        run: ls ../
      - name: List files up up
        run: ls ../../
          
